const $=id=>document.getElementById(id);
const J=x=>typeof x==='string'?x:JSON.stringify(x,null,2);
const out=(id,x)=>{const e=$(id);if(e)e.textContent=J(x)};
const body=f=>JSON.stringify(Object.fromEntries(new FormData(f).entries()));
const plat=x=>x==='X'?'Twitter':x;
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw Error(d.message||r.status);return d}
function err(e){let m=String(e?.message||e);if(m.includes('404'))return'API route not found. Pull latest code and restart backend.';if(m.toLowerCase().includes('fetch'))return'Backend is not running. Start uvicorn and open /app on port 8010.';return m}
let pack=null,cap='',user=null;
function openLogin(){$('loginModal')?.classList.add('open')}
function closeLogin(){$('loginModal')?.classList.remove('open')}
function handleLogout(){user=null;$('userPill')&&( $('userPill').textContent='Guest workspace');$('sidebarUserInfo')&&($('sidebarUserInfo').textContent='Not logged in');$('loginOpen')&&($('loginOpen').style.display='');$('logoutBtn')&&($('logoutBtn').style.display='none')}
window.openLogin=openLogin;window.handleLogout=handleLogout;
async function doLogin(e,id){e.preventDefault();try{let r=await api('/api/login',{method:'POST',body:body(e.currentTarget)});user=r.user||{};$('userPill')&&($('userPill').textContent=`${user.role}: ${user.username}`);$('sidebarUserInfo')&&($('sidebarUserInfo').textContent=`${user.role}: ${user.username}`);$('loginOpen')&&($('loginOpen').style.display='none');$('logoutBtn')&&($('logoutBtn').style.display='');out(id,{success:r.success,user:r.user});closeLogin()}catch(x){out(id,err(x))}}
function tab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.workspace').forEach(s=>s.classList.toggle('active',s.id===name));if(name==='analytics')analytics();if(name==='calendar')calendar();if(name==='admin'){adminTools();integrations();competitors()}}
function tags(x){return x?.hashtag_string||x?.hashtags?.join(' ')||x?.recommended_hashtags?.join(' ')||'#AI #SocialMedia'}
function score(x){return Number(x?.predicted_engagement_score??x?.score??0)}
function gauge(v){let g=$('predictionGauge');if(!g)return;v=Math.max(0,Math.min(100,Number(v)||0));let d=v/100*360;g.style.background=`radial-gradient(circle at center,#fff 0 58%,transparent 59%),conic-gradient(var(--primary) ${d}deg,#f0e6b8 ${d}deg)`;g.querySelector('span').textContent=v?Math.round(v):'--'}
function apply(p){pack=p;cap=p.caption||'';out('rawPostOutput',{caption:p.caption,hashtags:tags(p.hashtags),best_time:p.best_time,prediction:p.engagement_prediction,publish:p.publish_preview});out('captionOutput',cap);out('hashtagOutput',tags(p.hashtags));out('safetyOutput',{moderation:p.moderation,plagiarism:p.plagiarism});out('imagePromptOutput',p.image_prompt||{});gauge(score(p.engagement_prediction));out('predictionOutput',p.engagement_prediction||{});$('publishCaption')&&($('publishCaption').value=cap);$('dbCaption')&&($('dbCaption').value=cap)}
async function boot(){try{await api('/api/db/init')}catch{}try{let [h,c,d,i]=await Promise.all([api('/api/health'),api('/api/config'),api('/api/dataset-overview'),api('/api/integrations')]);$('apiStatus')&&($('apiStatus').textContent=h.status==='ok'?'Online':'Issue');$('postingMode')&&($('postingMode').textContent=c.posting_mode||'dry_run');$('postingModeBadge')&&($('postingModeBadge').textContent=c.posting_mode||'dry_run');$('datasetCount')&&($('datasetCount').textContent=(d.datasets||[]).length||'--');ready(i)}catch(x){$('apiStatus')&&($('apiStatus').textContent='Offline')}}
function ready(i={}){let e=$('platformReadiness');if(!e)return;e.innerHTML=['Instagram','Facebook','X','LinkedIn'].map(p=>`<article class="platform-card ok"><strong>${p}</strong><span>Backend connected. Dry-run safe.</span></article>`).join('')}
async function brief(){try{let p=plat($('briefPlatform')?.value||'Instagram');out('briefOutput',await api('/api/content/brief?platform='+encodeURIComponent(p)))}catch(x){out('briefOutput',err(x))}}
function injectCalendar(){let c=$('calendar');if(!c||$('dbCard'))return;let a=document.createElement('article');a.className='tool-card wide';a.id='dbCard';a.innerHTML=`<div class="card-head"><div><span>Database workflow</span><h3>Save, edit, approve, schedule, reschedule</h3></div><button class="ghost small" id="loadPosts">Load saved posts</button></div><div class="grid-2"><label>Post ID<input id="dbPost" type="number" placeholder="after save"></label><label>Title<input id="dbTitle" value="AI Social Studio post"></label></div><label>Editable caption<textarea id="dbCaption" rows="5">AI automation test caption #AI</textarea></label><div class="grid-2"><label>Platform<select id="dbPlatform"><option>Instagram</option><option>Facebook</option><option>X</option><option>LinkedIn</option></select></label><label>Hashtags<input id="dbTags" value="#AI #Automation"></label></div><div class="grid-2"><label>Date<input id="dbDate" type="date"></label><label>Time<input id="dbTime" type="time" value="19:00"></label></div><label>Reason<input id="dbReason" value="Better engagement slot"></label><div class="inline-actions"><button class="cta small" id="savePost">Save post</button><button class="ghost small" id="editPost">Edit post</button><button class="ghost small" id="submitPost">Submit approval</button><button class="cta small" id="schedulePost">Schedule</button><button class="ghost small" id="reschedulePost">Reschedule</button></div><pre id="dbOut">Ready. Connected to SQLite backend.</pre>`;c.appendChild(a);$('savePost').onclick=savePost;$('editPost').onclick=editPost;$('submitPost').onclick=submitPost;$('schedulePost').onclick=()=>schedule(false);$('reschedulePost').onclick=()=>schedule(true);$('loadPosts').onclick=async()=>out('dbOut',await api('/api/db/posts'))}
async function savePost(){try{let r=await api('/api/db/posts',{method:'POST',body:JSON.stringify({caption:$('dbCaption').value,platform:plat($('dbPlatform').value),hashtags:$('dbTags').value,title:$('dbTitle').value,created_by:user?.username||'editor_creator'})});$('dbPost').value=r.post?.post_id||'';out('dbOut',r);calendar()}catch(x){out('dbOut',err(x))}}
async function editPost(){try{let id=$('dbPost').value;out('dbOut',await api('/api/db/posts/'+id,{method:'PUT',body:JSON.stringify({caption:$('dbCaption').value,hashtags:$('dbTags').value,title:$('dbTitle').value,platform:plat($('dbPlatform').value)})}));calendar()}catch(x){out('dbOut',err(x))}}
async function submitPost(){try{out('dbOut',await api('/api/db/posts/'+$('dbPost').value+'/submit',{method:'POST'}));calendar()}catch(x){out('dbOut',err(x))}}
async function schedule(re){try{let id=Number($('dbPost').value);let d=$('dbDate').value,t=$('dbTime').value;if(!id||!d||!t)return out('dbOut','Post ID, date and time required.');let payload=re?{post_id:id,new_date:d,new_time:t,reason:$('dbReason').value}:{post_id:id,scheduled_date:d,scheduled_time:t};out('dbOut',await api(re?'/api/db/reschedule':'/api/db/schedule',{method:'POST',body:JSON.stringify(payload)}));calendar()}catch(x){out('dbOut',err(x))}}
async function calendar(){injectCalendar();try{let s=await api('/api/db/schedules');let rows=s.schedules||[];$('calendarLane').innerHTML=rows.slice(0,6).map(r=>`<article class="schedule-card"><strong>${r.platform}</strong><span>${r.scheduled_date||''} ${r.scheduled_time||''}</span><p>${String(r.caption||'').slice(0,110)}</p></article>`).join('');table('calendarTable',rows,['post_id','platform','scheduled_date','scheduled_time','post_status','caption'])}catch(x){out('calendarTable',err(x))}}
function adminTools(){let g=document.querySelector('#admin .card-grid');if(!g||$('reviewCard'))return;let h=document.createElement('article');h.className='tool-card wide';h.id='reviewCard';h.innerHTML=`<div class="card-head"><div><span>Feedback loop + approval</span><h3>Approve posts and store feedback</h3></div><button class="ghost small" id="loadReviews">Load feedback</button></div><div class="grid-2"><label>Post ID<input id="apPost" type="number" value="1"></label><label>Rating<input id="rating" type="number" min="1" max="5" value="5"></label></div><label>Notes<input id="notes" value="Good hook and CTA"></label><div class="inline-actions"><button class="cta small" id="approve">Approve</button><button class="ghost small" id="reject">Reject</button><button class="cta small" id="review">Save feedback</button></div><pre id="reviewOut">Ready. Connected to /api/db/approve and /api/db/review.</pre>`;g.appendChild(h);$('approve').onclick=()=>approve(true);$('reject').onclick=()=>approve(false);$('review').onclick=review;$('loadReviews').onclick=async()=>out('reviewOut',await api('/api/db/reviews'))}
async function approve(ok){try{out('reviewOut',await api('/api/db/approve',{method:'POST',body:JSON.stringify({post_id:Number($('apPost').value),approved:ok,reason:$('notes').value})}))}catch(x){out('reviewOut',err(x))}}
async function review(){try{out('reviewOut',await api('/api/db/review',{method:'POST',body:JSON.stringify({post_id:Number($('apPost').value)||null,platform:plat($('publishPlatform')?.value||'Instagram'),caption:$('publishCaption')?.value||cap,rating:Number($('rating').value),notes:$('notes').value})}))}catch(x){out('reviewOut',err(x))}}
function table(id,rows,cols){let e=$(id);if(!e)return;e.innerHTML='<thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${String(r[c]??'').slice(0,120)}</td>`).join('')+'</tr>').join('')+'</tbody>'}
async function analytics(){try{let [a,t]=await Promise.all([api('/api/analytics'),api('/api/trends')]);$('metricStrip').innerHTML=[['Posts',a.records],['Reach',a.total_reach],['Likes',a.total_likes],['Avg ER',a.avg_engagement_rate]].map(x=>`<article class="metric"><span>${x[0]}</span><strong>${x[1]??'--'}</strong><em>Analytics data</em></article>`).join('');$('engagementBars').innerHTML=(a.top_posts||[]).slice(0,12).map(p=>`<span class="bar" style="height:${Math.max(18,Number(p.engagement_rate)||20)}%"></span>`).join('');$('trendCloud').innerHTML=(t.trending_keywords||[]).slice(0,20).map(k=>`<span class="trend-chip">${k.keyword}</span>`).join('');table('topPostsTable',a.top_posts||[],['post_id','platform','likes','comments','shares','engagement_rate']);table('trendsTable',t.trending_keywords||[],['keyword','platform','trend_score','trend_category'])}catch(x){out('metricStrip',err(x))}}
async function competitors(){try{out('competitorOutput',await api('/api/competitors'))}catch(x){out('competitorOutput',err(x))}}
async function integrations(){try{let d=await api('/api/integrations');$('integrationStatus').innerHTML=['Telegram','LinkedIn','X'].map(n=>`<span class="integration-pill ok"><strong>${n}</strong><span>checked</span></span>`).join('')}catch(x){out('integrationStatus',err(x))}}
function wire(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>tab(b.dataset.jump));$('loginOpen')&&($('loginOpen').onclick=openLogin);$('loginClose')&&($('loginClose').onclick=closeLogin);$('logoutBtn')&&($('logoutBtn').onclick=handleLogout);$('sidebarLoginBtn')&&($('sidebarLoginBtn').onclick=()=>user?handleLogout():openLogin());$('topLoginForm')&&($('topLoginForm').onsubmit=e=>doLogin(e,'topLoginOutput'));$('loginForm')&&($('loginForm').onsubmit=e=>doLogin(e,'loginOutput'));$('loadBriefButton')&&($('loadBriefButton').onclick=brief);$('briefPlatform')&&($('briefPlatform').onchange=brief);$('refreshCalendar')&&($('refreshCalendar').onclick=calendar);$('rawPostForm')&&($('rawPostForm').onsubmit=async e=>{e.preventDefault();try{let p=Object.fromEntries(new FormData(e.currentTarget).entries());p.platform=plat(p.platform);apply(await api('/api/full-pipeline',{method:'POST',body:JSON.stringify(p)}))}catch(x){out('rawPostOutput',err(x))}});$('generateForm')&&($('generateForm').onsubmit=async e=>{e.preventDefault();try{let p=Object.fromEntries(new FormData(e.currentTarget).entries());p.platform=plat(p.platform);let c=await api('/api/generate-caption',{method:'POST',body:JSON.stringify(p)});cap=c.caption||c.captions?.[0]?.caption||J(c);out('captionOutput',cap);let [ha,mo,pl,im]=await Promise.all([api('/api/hashtags',{method:'POST',body:JSON.stringify({text:cap,platform:p.platform})}),api('/api/moderate',{method:'POST',body:JSON.stringify({text:cap,platform:p.platform})}),api('/api/plagiarism',{method:'POST',body:JSON.stringify({text:cap,platform:p.platform})}),api('/api/image-prompt',{method:'POST',body:JSON.stringify(p)})]);out('hashtagOutput',tags(ha));out('safetyOutput',{moderation:mo,plagiarism:pl});out('imagePromptOutput',im)}catch(x){out('captionOutput',err(x))}});$('predictForm')&&($('predictForm').onsubmit=async e=>{e.preventDefault();try{let p=Object.fromEntries(new FormData(e.currentTarget).entries());p.platform=plat(p.platform);p.hour_posted=Number(p.hour_posted);p.hashtags=(p.caption.match(/#\w+/g)||[]).join(' ');p.sentiment_score=.7;p.has_image=1;let r=await api('/api/predict-engagement',{method:'POST',body:JSON.stringify(p)});gauge(score(r));out('predictionOutput',r)}catch(x){out('predictionOutput',err(x))}});$('publishButton')&&($('publishButton').onclick=async()=>{try{out('publishOutput',await api('/api/publish',{method:'POST',body:JSON.stringify({platform:plat($('publishPlatform').value),caption:$('publishCaption').value,media_url:$('publishMediaUrl').value||null})}))}catch(x){out('publishOutput',err(x))}});$('telegramButton')&&($('telegramButton').onclick=async()=>{try{out('publishOutput',await api('/api/telegram',{method:'POST',body:JSON.stringify({message:$('publishCaption').value})}))}catch(x){out('publishOutput',err(x))}})}
wire();boot();injectCalendar();adminTools();